[platformio]
default_envs = receiver_node

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_ldf_mode = deep+

[env:sensor_node]
build_src_filter = +<sensor_node_main.cpp>

[env:receiver_node]
build_src_filter = +<receiver_node_main.cpp>
