[platformio]
description = KX134 receiver ESP32 identity capture
default_envs = receiver_identity

[env:receiver_identity]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 921600
